###  POST /register
POST http://localhost:8080/api/user/register
Content-Type: application/json

{
  "login": "temp12",
  "password": "12345"
}

###  POST /login
POST http://localhost:8080/api/user/login
Content-Type: application/json

{
  "login": "temp12",
  "password": "12345"
}

###  POST /orders
POST http://localhost:8080/api/user/orders
Content-Type: text/plain
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Nzk0Mjg4MzcsInN1YiI6InRlbXAxNiJ9.IXyNwFOkIAoY_N08sgj26XxwTGMHKI3tRC5x3dvgj6Q

12345678903

###  GET /orders
GET http://localhost:8080/api/user/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Nzk0MzA3NzYsInN1YiI6InRlbXAxMiJ9.6Omdf3yAzc8b6NiSFV3sx4v8y7IUGjLdpeKOmOApupE


